### ISSUE TITLE
Flags Not Appearing for a Handful of Countries

### ISSUE THREAD

**Issue by EmperorNuclear** [vawser/Game-of-Thrones-Mod#17]
Countries in the Reach are missing flags for some reason and it hasn't affected any of the other houses. Might be a simple fix, but I will log it here so I don't forget to fix the issue.

![Screenshot 2023-04-22 210355](https://user-images.githubusercontent.com/114454346/233819269-40ba24b0-92d1-44e5-97c2-a1045efde0ae.png)

**Comment by EmperorNuclear** [comment]
Issue has been identified. Will be fixed prior to release.

![Screenshot 2023-04-22 233940](https://user-images.githubusercontent.com/114454346/233824083-c5a34b6c-8d2b-47e5-9e03-6ff2808834a7.png)

**Comment by theolaa** [comment]
Closed by 79f37e9f180e6e9a82ec97f39de49647b3e38054
