### ISSUE TITLE
Problems with Iron Throne mechanics

### ISSUE THREAD

**Issue by theolaa** [vawser/Game-of-Thrones-Mod#6]
Played as Stark in the shattered world start date.
I took Kings landing and the iron throne transferred to me just fine.
Rebels appeared in Kingslanding and i let them take to see what would happen.
The Iron throne mechanic disappeared but i still had some royal subjects and claims on all of Westeros.
When I took Kingslanding back, the Iron Throne was reinstated but the mechanic button on the bottom did not come back. The notification that i had enough meritocracy to enact a policy appeared but it did not elad me anywhere.

Not giving kingslanding to the besieger really breaks the immersion.
In order to take the city, you need to defeat all enemies, take all territories, but Targaryans in Kingslanding then take that city last. Peace out before the event auto-resolves itself and then select the event.

Kind of ruins the game tbh.

**Comment by EmperorNuclear** [comment]
Going to prioritize this.
