### ISSUE TITLE
Name of the kingdoms and provinces is wrong or dont macht

### ISSUE THREAD

**Issue by arigita999** [vawser/Game-of-Thrones-Mod#8]
for example the crownlands provinces are the iberia region ones. How could I fix this? thank you

**Comment by arigita999** [comment]
Also if I start the game it crash. Maybe is because I am playing in Epic Games

**Comment by theolaa** [comment]
I'm sorry, I forgot to update the mod on Paradox mods. When you get the update it will fix both these problems (assuming you're on EU4 1.34)

**Comment by arigita999** [comment]
I am in the 1.34.4
